config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :albums
  devise_for :users

  root 'home#index'
  get 'home/allalbum' => 'home#allalbum'

end

app/models/album.rb
class Album < ActiveRecord::Base

  belongs_to :user
  has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base

  belongs_to :album
  belongs_to :user
  
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :albums
  has_many :images
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [ :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = current_user.albums
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])
    @images = @album.images
  end

  # GET /albums/new
  def new
    @album = current_user.albums.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = current_user.albums.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    current_user.album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = current_user.albums.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @images = Image.order('id desc').limit(25)
  end

  def allalbum
  	@albums = Album.all
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:edit, :update, :destroy]

  # GET /images
  # GET /images.json
  #def onlyimage
  #  @album = Album.find(params[:album_id])
  #  @image = @album.images
  #end

  def index
    @images = current_user.images
  end

  # GET /images/1
  # GET /images/1.json
  def show
         @image = Image.find(params[:id])
  end

  # GET /images/new
  def new
  	@user_id = current_user.id
    @album = Album.find(params[:album_id])
    @image = @album.images.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
  	
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image

      @image = Image.find(params[:id])
      @album = current_user.albums.find(@image.album_id)

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :tag_line, :album_id, :user_id, :avatar)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/albums/_form.html.haml
= form_for @album, :html => { :class => 'form-horizontal' } do |f|
  .form-group
    = f.label :name, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :name, :class => 'text_field form-control'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), |
        albums_path, :class => 'btn btn-default'                     |

app/views/albums/edit.html.haml
- model_class = Album
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/albums/index.html.haml
- model_class = Album
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @albums.each do |album|
      %tr
        %td= album.id
        %td= album.name
        %td= l album.created_at, format: :long
        %td
          = link_to album_path(album), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do
            = glyph 'info-sign'
          = link_to edit_album_path(album), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do
            = glyph 'pencil'
          = link_to album_path(album), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do
            = glyph 'remove'
= link_to t('.new', :default => t("helpers.links.new")), |
  new_album_path,                                        |
  :class => 'btn btn-primary'                            |

app/views/albums/new.html.haml
- model_class = Album
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/albums/show.html.haml
- model_class = Album
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
.fieldset
  %dl
    %dt.label.label-default= model_class.human_attribute_name(:name)
    %dd
      %pre.prettyprint= @album.name
  %dl
    %dt.label "Images"
    %dd
      = render 'images/index'
.form-group
  = link_to t('.back', :default => t("helpers.links.back")), albums_path, :class => 'btn btn-default'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_album_path(@album), :class => 'btn btn-default'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), album_path(@album), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

= link_to "Create Image", new_image_path(album_id: @album.id), :class => 'btn btn-primary'

app/views/home/allalbum.html.haml
- model_class = Album
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
  %tbody
    - @albums.each do |album|
      %tr
      %br
        %td= album.user.email
        %td= album.name
        %td= l album.created_at, format: :long
        %td
          = link_to album_path(album), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do
            = glyph 'info-sign'

app/views/home/index.html.haml
= link_to 'My Albums', albums_path, :class => 'btn btn-default'
= link_to 'All Albums', 'home/allalbum', :class => 'btn btn-default'
- @images.each do |image|
  %br
  %tr
    / %td= image.user.email
    / %td= image.name
    / %td= image.tag_line
    / %td= l image.created_at, format: :long
    %td= image_tag image.avatar.url(:medium)
    %td
  %br 

app/views/images/_form.html.haml
= form_for @image, :html => { :multipart => true, :class => 'form-horizontal' } do |f|
  .form-group
    = f.label :name, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :name, :class => 'text_field form-control'
  .form-group
    = f.label :tag_line, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :tag_line, :class => 'text_field form-control'
  .form-group
    = f.label :photo, :class => 'control-label col-md-2'
    .col-md-10
      = f.file_field :avatar
  .form-group
    .col-md-offset-2.col-md-10
      = f.hidden_field :album_id, value: @album.id
      = f.hidden_field :user_id, value: @user_id
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")),images_path, :class => 'btn btn-default'

app/views/images/_index.html.haml
- @images.each do |image|
  %tr
    %td= image.name
    %td= image.tag_line
    %td= image_tag image.avatar.url(:medium)
    %td= l image.created_at, format: :long
    %td
  = link_to image_path(image), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do
    = glyph 'info-sign'
  = link_to edit_image_path(image), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do
    = glyph 'pencil'
  = link_to image_path(image), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do
    = glyph 'remove'
  %br 

app/views/images/edit.html.haml
- model_class = Image
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/images/index.html.haml
- model_class = Image
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:tag_line)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @images.each do |image|
      %tr
        %td= image.id
        %td= image.name
        %td= image.tag_line
        %td= l image.created_at, format: :long
        %td
          = link_to image_path(image), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do
            = glyph 'info-sign'
          = link_to edit_image_path(image), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do
            = glyph 'pencil'
          = link_to image_path(image), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do
            = glyph 'remove'

app/views/images/new.html.haml
- model_class = Image
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/images/show.html.haml
- model_class = Image
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
.fieldset
  %dl
    %dt.label.label-default= model_class.human_attribute_name(:name)
    %dd
      %pre.prettyprint= @image.name
    %dt.label.label-default= model_class.human_attribute_name(:tag_line)
    %dd
      %pre.prettyprint= @image.tag_line
    %dt.label.label-default= model_class.human_attribute_name(:avatar)
    %dd
      %pre.prettyprint= image_tag @image.avatar.url(:thumb)

.form-group
  = link_to t('.edit', :default => t("helpers.links.edit")),edit_image_path(@image), :class => 'btn btn-default'
  = link_to t('.destroy', :default => t("helpers.links.destroy")),
    image_path(@image),
    :method => 'delete',
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
    :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    = viewport_meta_tag
    %title= content_for?(:title) ? yield(:title) : "PMS"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  %body
    %nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
      .container
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} Image Upload Tool
        / Collect the nav links, forms, and other content for toggling
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav
            %li.active
              %p.navbar-text.pull-right
                - if user_signed_in?
                  Logged in as
                  = succeed "." do
                    %strong= current_user.email
                  = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
                  |
                  \#{link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
                - else
                  = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
                  |
                  \#{link_to "Login", new_user_session_path, :class => 'navbar-link'}

        / /.navbar-collapse
    .container
      .row
        .col-md-12
          = bootstrap_flash
          = yield
          -# %ul.nav.navbar-nav
          -#  - if notice
          -#    %p.alert.alert-success= notice
          -#  - if alert
          -#    %p.alert.alert-danger= alert
        -# .col-md-3
        -#   .well.sidebar-nav
        -#     %h3 Sidebar
        -#     %ul.nav.nav-list
        -#       %li.nav-header Sidebar
        -#       %li= link_to "Link1", "#"
        -#       %li= link_to "Link2", "#"
        -#       %li= link_to "Link3", "#"
          / /.well
        / /span
      / /row
      %footer
        %p © PMS.
    / /container